[package]
distribution = "slbeta3"
org = "ballerinax"
name = "mysql"
version = "1.5.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "MySQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mysql"
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "C://Ballerina modules//module-ballerinax-java.jdbc-1.5.0"

[[platform.java11.dependency]]
path = "C://jar_files//mysql-connector-java-8.0.30.jar"
scope = "testOnly"